name: deploy S3

on:
  push:
    branch: main

env:
  NODE_VERSION: 18.x
  INSTALL_COMMAND: yarn install
  BUILD_COMMAND: yarn build
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: tag.blog

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: set node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: dependency install
        run: ${{ env.INSTALL_COMMAND }}
      - name: build
        run: ${{ env.BUILD_COMMAND }}
      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: aws s3 cp --recursive --region ${{ env.AWS_REGION }} build s3://${{ env.AWS_S3_BUCKET }}
